### ISSUE TITLE
Identificar comunidades focadas em processos abertos

### ISSUE THREAD

**Issue by waldyrious** [zorkpt/comunidades-tech-portugal#3]
Vejo que por exemplo a ANSOL e a D3 estão listadas na secção "Comunidades Gerais". Se calhar faria sentido termos uma secção específica para "open software/media/data"? Não sei bem como chamar a isto, mas acho que pode fazer sentido.

**Comment by gvlx** [comment]
Isto também juntaria a PrivacyLx, Creative Commons, Transparência Portugal?

**Comment by zorkpt** [comment]
acho boa ideia 👍 podes fazer o pull request?
talvez Software Livre, Média e Dados Abertos ?

**Comment by waldyrious** [comment]
Sim, todos esses eu diria :D Posso criar o PR, talvez no fds.

**Comment by marado** [comment]
A ANSOL também mantém uma lista de comunidades que pode fazer sentido "importar" para aqui: https://ansol.org/noticias/2012-03-30-comunidades-portuguesas-de-software-livre/
